# Generated by Django 4.2.4 on 2023-08-23 01:14

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries =   {
        "published": "A post that appears to the public",
        "draft": "A post only the author can see", 
        "archived": "A post that was previously available to the public"
    }

    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
